ce204_hw4_library_observeMethod.ReservationSubject Class Reference
Public Member Functions
void attachObserver (ReservationObserver observer)
void detachObserver (ReservationObserver observer)
void notifyObservers (String message)
List< ReservationObserver > getObservers ()
Detailed Description
Definition at line 6 of file ReservationSubject.java.
Member Function Documentation
attachObserver()
void ce204_hw4_library_observeMethod.ReservationSubject.attachObserver (ReservationObserver observer)
Attaches an observer to the reservation subject.
Parameters
observer the observer to be attached
Definition at line 14 of file ReservationSubject.java.
                                                             {
        observers.add(observer);
    }
Referenced by ce204_hw4_library_observeMethod.CarReservationSystem.addUser(), ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testAttachObserver(), ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testDetachObserver(), and ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testNotifyObservers().
detachObserver()
void ce204_hw4_library_observeMethod.ReservationSubject.detachObserver (ReservationObserver observer)
Detaches an observer from the reservation subject.
Parameters
observer the observer to be detached
Definition at line 22 of file ReservationSubject.java.
                                                             {
        observers.remove(observer);
    }
Referenced by ce204_hw4_library_observeMethod.CarReservationSystem.removeUser(), and ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testDetachObserver().
getObservers()
List< ReservationObserver > ce204_hw4_library_observeMethod.ReservationSubject.getObservers ()
Returns a list of observers attached to the reservation subject.
Returns
the list of observers
Definition at line 40 of file ReservationSubject.java.
                                                    {
        return observers;
    }
Referenced by ce204_hw4_library_observeMethod.CarReservationSystem.getObservers(), ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testAttachObserver(), and ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testDetachObserver().
notifyObservers()
void ce204_hw4_library_observeMethod.ReservationSubject.notifyObservers (String message)
Notifies all observers with the specified message.
Parameters
message the message to notify the observers
Definition at line 30 of file ReservationSubject.java.
                                                {
        for (ReservationObserver observer : observers) {
            observer.notifyReservation(message);
        }
    }
Referenced by ce204_hw4_library_observeMethod.CarReservationSystem.makeReservation(), and ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testNotifyObservers().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library_observeMethod/ReservationSubject.java