ce204_hw4_librar_factoryMethod.LuxuryCarRental Class Reference
Public Member Functions
LuxuryCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
void rentCar ()
int getMileage ()
int getPrice ()
String getBrand ()
String getModel ()
int getYear ()
String getFuelType ()
String getGear ()
String getColor ()
Detailed Description
Definition at line 3 of file LuxuryCarRental.java.
Constructor & Destructor Documentation
LuxuryCarRental()
ce204_hw4_librar_factoryMethod.LuxuryCarRental.LuxuryCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
Constructs a LuxuryCarRental object with the specified details.
Parameters
mileage the mileage of the car
brand the brand of the car
model the model of the car
year the year of the car
fuelType the fuel type of the car
gear the transmission type of the car
color the color of the car
price the price of the car rental
Definition at line 26 of file LuxuryCarRental.java.
                                                                                                                                     {
        this.mileage = mileage;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.fuelType = fuelType;
        this.gear = gear;
        this.color = color;
        this.price = price;
    }
Member Function Documentation
getBrand()
String ce204_hw4_librar_factoryMethod.LuxuryCarRental.getBrand ()
Returns the brand of the car.
Returns
the brand of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 76 of file LuxuryCarRental.java.
                             {
        // TODO Auto-generated method stub
        return brand;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetBrand().
getColor()
String ce204_hw4_librar_factoryMethod.LuxuryCarRental.getColor ()
Returns the color of the car.
Returns
the color of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 126 of file LuxuryCarRental.java.
                             {
        // TODO Auto-generated method stub
        return color;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetColor().
getFuelType()
String ce204_hw4_librar_factoryMethod.LuxuryCarRental.getFuelType ()
Returns the fuel type of the car.
Returns
the fuel type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 106 of file LuxuryCarRental.java.
                                {
        // TODO Auto-generated method stub
        return fuelType;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetFuelType().
getGear()
String ce204_hw4_librar_factoryMethod.LuxuryCarRental.getGear ()
Returns the transmission type of the car.
Returns
the transmission type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 116 of file LuxuryCarRental.java.
                            {
        // TODO Auto-generated method stub
        return gear;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetGear().
getMileage()
int ce204_hw4_librar_factoryMethod.LuxuryCarRental.getMileage ()
Returns the mileage of the car.
Returns
the mileage of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 56 of file LuxuryCarRental.java.
                            {
        // TODO Auto-generated method stub
        return mileage;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetMileage().
getModel()
String ce204_hw4_librar_factoryMethod.LuxuryCarRental.getModel ()
Returns the model of the car.
Returns
the model of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 86 of file LuxuryCarRental.java.
                             {
        // TODO Auto-generated method stub
        return model;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetModel().
getPrice()
int ce204_hw4_librar_factoryMethod.LuxuryCarRental.getPrice ()
Returns the price of the car rental.
Returns
the price of the car rental
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 66 of file LuxuryCarRental.java.
                          {
        // TODO Auto-generated method stub
        return price;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetPrice().
getYear()
int ce204_hw4_librar_factoryMethod.LuxuryCarRental.getYear ()
Returns the year of the car.
Returns
the year of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 96 of file LuxuryCarRental.java.
                         {
        // TODO Auto-generated method stub
        return year;
    }
Referenced by ce204_hw4_LuxuryCarTest.testGetYear().
rentCar()
void ce204_hw4_librar_factoryMethod.LuxuryCarRental.rentCar ()
Rents the luxury car.
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 44 of file LuxuryCarRental.java.
                          {
        // TODO Auto-generated method stub
        System.out.println("Brand: " + brand + ", Model: " + model + ", Year: " + year +
                ", Fuel Type: " + fuelType + ", Gear: " + gear + ", Color: " + color +
                ", Mileage: " + mileage + ", Price: " + price);
    }
Referenced by ce204_hw4_LuxuryCarTest.testRentCar().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_librar_factoryMethod/LuxuryCarRental.java