ce204_hw4_librar_factoryMethod.EconomyCarRental Class Reference
Public Member Functions
EconomyCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
void rentCar ()
int getPrice ()
int getMileage ()
String getBrand ()
String getModel ()
int getYear ()
String getFuelType ()
String getGear ()
String getColor ()
Detailed Description
Definition at line 3 of file EconomyCarRental.java.
Constructor & Destructor Documentation
EconomyCarRental()
ce204_hw4_librar_factoryMethod.EconomyCarRental.EconomyCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
Constructs an EconomyCarRental object with the specified details.
Parameters
mileage the mileage of the car
brand the brand of the car
model the model of the car
year the year of the car
fuelType the fuel type of the car
gear the transmission type of the car
color the color of the car
price the price of the car rental
Definition at line 26 of file EconomyCarRental.java.
                                                                                                                                      {
        this.mileage = mileage;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.fuelType = fuelType;
        this.gear = gear;
        this.color = color;
        this.price = price;
    }
Member Function Documentation
getBrand()
String ce204_hw4_librar_factoryMethod.EconomyCarRental.getBrand ()
Returns the brand of the car.
Returns
the brand of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 78 of file EconomyCarRental.java.
                             {
        // TODO Auto-generated method stub
        return brand;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetBrand().
getColor()
String ce204_hw4_librar_factoryMethod.EconomyCarRental.getColor ()
Returns the color of the car.
Returns
the color of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 128 of file EconomyCarRental.java.
                             {
        // TODO Auto-generated method stub
        return color;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetColor().
getFuelType()
String ce204_hw4_librar_factoryMethod.EconomyCarRental.getFuelType ()
Returns the fuel type of the car.
Returns
the fuel type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 108 of file EconomyCarRental.java.
                                {
        // TODO Auto-generated method stub
        return fuelType;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetFuelType().
getGear()
String ce204_hw4_librar_factoryMethod.EconomyCarRental.getGear ()
Returns the gear type of the car.
Returns
the gear type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 118 of file EconomyCarRental.java.
                            {
        // TODO Auto-generated method stub
        return gear;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetGear().
getMileage()
int ce204_hw4_librar_factoryMethod.EconomyCarRental.getMileage ()
Returns the mileage of the car.
Returns
the mileage of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 68 of file EconomyCarRental.java.
                            {
        // TODO Auto-generated method stub
        return mileage;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetMileage().
getModel()
String ce204_hw4_librar_factoryMethod.EconomyCarRental.getModel ()
Returns the model of the car.
Returns
the model of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 88 of file EconomyCarRental.java.
                             {
        // TODO Auto-generated method stub
        return model;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetModel().
getPrice()
int ce204_hw4_librar_factoryMethod.EconomyCarRental.getPrice ()
Returns the price of the car rental.
Returns
the price of the car rental
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 56 of file EconomyCarRental.java.
                          {
        // TODO Auto-generated method stub
        return price;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetPrice().
getYear()
int ce204_hw4_librar_factoryMethod.EconomyCarRental.getYear ()
Returns the year of the car.
Returns
the year of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 98 of file EconomyCarRental.java.
                         {
        // TODO Auto-generated method stub
        return year;
    }
Referenced by ce204_hw4_EconomyCarTest.testGetYear().
rentCar()
void ce204_hw4_librar_factoryMethod.EconomyCarRental.rentCar ()
Rents the economy car.
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 44 of file EconomyCarRental.java.
                          {
        // TODO Auto-generated method stub
        System.out.println("Brand: " + brand + ", Model: " + model + ", Year: " + year +
                ", Fuel Type: " + fuelType + ", Transmission: " + gear + ", Color: " + color +
                ", Mileage: " + mileage + ", Price: " + price);
    }
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_librar_factoryMethod/EconomyCarRental.java