ce204_hw4_RentalFactoryTest Class Reference
Public Member Functions
void testCreateRental_EconomyCar ()
Test case for creating an economy car rental.
void testCreateRental_LuxuryCar ()
Test case for creating a luxury car rental.
void testCreateRental_SuvCar ()
Test case for creating an SUV car rental.
Detailed Description
Definition at line 9 of file ce204_hw4_RentalFactoryTest.java.
Member Function Documentation
testCreateRental_EconomyCar()
void ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar ()
Test case for creating an economy car rental.
Definition at line 15 of file ce204_hw4_RentalFactoryTest.java.
                                              {
        // Test data
        String type = "economy";
        int mileage = 10000;
        String brand = "Toyota";
        String model = "Corolla";
        int year = 2020;
        String fuelType = "Gasoline";
        String gear = "Automatic";
        String color = "Red";
        int price = 50;
        // Create an instance of RentalFactory
        RentalFactory rentalFactory = new RentalFactory();
        // Create an economy car rental using the factory
        ICarRental carRental = rentalFactory.createRental(type, mileage, brand, model, year, fuelType, gear, color, price);
        // Assert that the carRental instance is of type EconomyCarRental
        Assert.assertTrue(carRental instanceof EconomyCarRental);
        // Assert the property values of the carRental instance
        Assert.assertEquals(mileage, carRental.getMileage());
        Assert.assertEquals(brand, carRental.getBrand());
        Assert.assertEquals(model, carRental.getModel());
        Assert.assertEquals(year, carRental.getYear());
        Assert.assertEquals(fuelType, carRental.getFuelType());
        Assert.assertEquals(gear, carRental.getGear());
        Assert.assertEquals(color, carRental.getColor());
        Assert.assertEquals(price, carRental.getPrice());
    }
References ce204_hw4_librar_factoryMethod.RentalFactory.createRental(), ce204_hw4_librar_factoryMethod.ICarRental.getBrand(), ce204_hw4_librar_factoryMethod.ICarRental.getColor(), ce204_hw4_librar_factoryMethod.ICarRental.getFuelType(), ce204_hw4_librar_factoryMethod.ICarRental.getGear(), ce204_hw4_librar_factoryMethod.ICarRental.getMileage(), ce204_hw4_librar_factoryMethod.ICarRental.getModel(), ce204_hw4_librar_factoryMethod.ICarRental.getPrice(), and ce204_hw4_librar_factoryMethod.ICarRental.getYear().
testCreateRental_LuxuryCar()
void ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar ()
Test case for creating a luxury car rental.
Definition at line 51 of file ce204_hw4_RentalFactoryTest.java.
                                             {
        // Test data
        String type = "luxury";
        int mileage = 5000;
        String brand = "Mercedes";
        String model = "S-Class";
        int year = 2022;
        String fuelType = "Diesel";
        String gear = "Automatic";
        String color = "Black";
        int price = 150;
        // Create an instance of RentalFactory
        RentalFactory rentalFactory = new RentalFactory();
        // Create a luxury car rental using the factory
        ICarRental carRental = rentalFactory.createRental(type, mileage, brand, model, year, fuelType, gear, color, price);
        // Assert that the carRental instance is of type LuxuryCarRental
        Assert.assertTrue(carRental instanceof LuxuryCarRental);
        // Assert the property values of the carRental instance
        Assert.assertEquals(mileage, carRental.getMileage());
        Assert.assertEquals(brand, carRental.getBrand());
        Assert.assertEquals(model, carRental.getModel());
        Assert.assertEquals(year, carRental.getYear());
        Assert.assertEquals(fuelType, carRental.getFuelType());
        Assert.assertEquals(gear, carRental.getGear());
        Assert.assertEquals(color, carRental.getColor());
        Assert.assertEquals(price, carRental.getPrice());
    }
References ce204_hw4_librar_factoryMethod.RentalFactory.createRental(), ce204_hw4_librar_factoryMethod.ICarRental.getBrand(), ce204_hw4_librar_factoryMethod.ICarRental.getColor(), ce204_hw4_librar_factoryMethod.ICarRental.getFuelType(), ce204_hw4_librar_factoryMethod.ICarRental.getGear(), ce204_hw4_librar_factoryMethod.ICarRental.getMileage(), ce204_hw4_librar_factoryMethod.ICarRental.getModel(), ce204_hw4_librar_factoryMethod.ICarRental.getPrice(), and ce204_hw4_librar_factoryMethod.ICarRental.getYear().
testCreateRental_SuvCar()
void ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar ()
Test case for creating an SUV car rental.
Definition at line 87 of file ce204_hw4_RentalFactoryTest.java.
                                          {
        // Test data
        String type = "suv";
        int mileage = 20000;
        String brand = "Jeep";
        String model = "Wrangler";
        int year = 2021;
        String fuelType = "Gasoline";
        String gear = "Manual";
        String color = "Yellow";
        int price = 80;
        // Create an instance of RentalFactory
        RentalFactory rentalFactory = new RentalFactory();
        // Create an SUV car rental using the factory
        ICarRental carRental = rentalFactory.createRental(type, mileage, brand, model, year, fuelType, gear, color, price);
        // Assert that the carRental instance is of type SuvCarRental
        Assert.assertTrue(carRental instanceof SuvCarRental);
        // Assert the property values of the carRental instance
        Assert.assertEquals(mileage, carRental.getMileage());
        Assert.assertEquals(brand, carRental.getBrand());
        Assert.assertEquals(model, carRental.getModel());
        Assert.assertEquals(year, carRental.getYear());
        Assert.assertEquals(fuelType, carRental.getFuelType());
        Assert.assertEquals(gear, carRental.getGear());
        Assert.assertEquals(color, carRental.getColor());
        Assert.assertEquals(price, carRental.getPrice());
    }
References ce204_hw4_librar_factoryMethod.RentalFactory.createRental(), ce204_hw4_librar_factoryMethod.ICarRental.getBrand(), ce204_hw4_librar_factoryMethod.ICarRental.getColor(), ce204_hw4_librar_factoryMethod.ICarRental.getFuelType(), ce204_hw4_librar_factoryMethod.ICarRental.getGear(), ce204_hw4_librar_factoryMethod.ICarRental.getMileage(), ce204_hw4_librar_factoryMethod.ICarRental.getModel(), ce204_hw4_librar_factoryMethod.ICarRental.getPrice(), and ce204_hw4_librar_factoryMethod.ICarRental.getYear().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_RentalFactoryTest.java