ce204_hw4_SUVCarTest Class Reference
Public Member Functions
void setUp ()
Set up the test environment.
void testGetMileage ()
Test case for getting the mileage.
void testGetBrand ()
Test case for getting the brand.
void testGetModel ()
Test case for getting the model.
void testGetYear ()
Test case for getting the year.
void testGetFuelType ()
Test case for getting the fuel type.
void testGetGear ()
Test case for getting the gear.
void testGetColor ()
Test case for getting the color.
void testGetPrice ()
Test case for getting the price.
void testRentCar ()
Test case for renting a car.
Detailed Description
Definition at line 13 of file ce204_hw4_SUVCarTest.java.
Member Function Documentation
setUp()
void ce204_hw4_SUVCarTest.setUp ()
Set up the test environment.
Definition at line 21 of file ce204_hw4_SUVCarTest.java.
                        {
        carRental = new SuvCarRental(10000, "Toyota", "Corolla", 2020, "Gasoline", "Automatic", "Red", 50);
    }
testGetBrand()
void ce204_hw4_SUVCarTest.testGetBrand ()
Test case for getting the brand.
Definition at line 39 of file ce204_hw4_SUVCarTest.java.
                               {
        String expectedBrand = "Toyota";
        String actualBrand = carRental.getBrand();
        Assert.assertEquals(expectedBrand, actualBrand);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getBrand().
testGetColor()
void ce204_hw4_SUVCarTest.testGetColor ()
Test case for getting the color.
Definition at line 89 of file ce204_hw4_SUVCarTest.java.
                               {
        String expectedColor = "Red";
        String actualColor = carRental.getColor();
        Assert.assertEquals(expectedColor, actualColor);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getColor().
testGetFuelType()
void ce204_hw4_SUVCarTest.testGetFuelType ()
Test case for getting the fuel type.
Definition at line 69 of file ce204_hw4_SUVCarTest.java.
                                  {
        String expectedFuelType = "Gasoline";
        String actualFuelType = carRental.getFuelType();
        Assert.assertEquals(expectedFuelType, actualFuelType);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getFuelType().
testGetGear()
void ce204_hw4_SUVCarTest.testGetGear ()
Test case for getting the gear.
Definition at line 79 of file ce204_hw4_SUVCarTest.java.
                              {
        String expectedGear = "Automatic";
        String actualGear = carRental.getGear();
        Assert.assertEquals(expectedGear, actualGear);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getGear().
testGetMileage()
void ce204_hw4_SUVCarTest.testGetMileage ()
Test case for getting the mileage.
Definition at line 29 of file ce204_hw4_SUVCarTest.java.
                                 {
        int expectedMileage = 10000;
        int actualMileage = carRental.getMileage();
        Assert.assertEquals(expectedMileage, actualMileage);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getMileage().
testGetModel()
void ce204_hw4_SUVCarTest.testGetModel ()
Test case for getting the model.
Definition at line 49 of file ce204_hw4_SUVCarTest.java.
                               {
        String expectedModel = "Corolla";
        String actualModel = carRental.getModel();
        Assert.assertEquals(expectedModel, actualModel);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getModel().
testGetPrice()
void ce204_hw4_SUVCarTest.testGetPrice ()
Test case for getting the price.
Definition at line 99 of file ce204_hw4_SUVCarTest.java.
                               {
        int expectedPrice = 50;
        int actualPrice = carRental.getPrice();
        Assert.assertEquals(expectedPrice, actualPrice);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getPrice().
testGetYear()
void ce204_hw4_SUVCarTest.testGetYear ()
Test case for getting the year.
Definition at line 59 of file ce204_hw4_SUVCarTest.java.
                              {
        int expectedYear = 2020;
        int actualYear = carRental.getYear();
        Assert.assertEquals(expectedYear, actualYear);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.getYear().
testRentCar()
void ce204_hw4_SUVCarTest.testRentCar ()
Test case for renting a car.
Definition at line 109 of file ce204_hw4_SUVCarTest.java.
                              {
        int mileage = 5000;
        String brand = "Mercedes";
        String model = "S-Class";
        int year = 2022;
        String fuelType = "Gasoline";
        String gear = "Automatic";
        String color = "Black";
        int price = 100;
        SuvCarRental carRental = new SuvCarRental(mileage, brand, model, year, fuelType, gear, color, price);
        String expectedOutput = "Brand: Mercedes, Model: S-Class, Year: 2022, Fuel Type: Gasoline, Gear: Automatic, Color: Black, Mileage: 5000, Price: 100";
        String actualOutput = captureSystemOut(() -> carRental.rentCar());
        Assert.assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_librar_factoryMethod.SuvCarRental.rentCar().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_SUVCarTest.java