ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest Class Reference
Public Member Functions
void setUp ()
Set up the test environment.
void testAttachObserver ()
Test case for attaching an observer.
void testDetachObserver ()
Test case for detaching an observer.
void testNotifyObservers ()
Test case for notifying observers.
Detailed Description
Definition at line 12 of file ce204_hw4_ReservationSubjectTest.java.
Member Function Documentation
setUp()
void ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.setUp ()
Set up the test environment.
Definition at line 21 of file ce204_hw4_ReservationSubjectTest.java.
                        {
        subject = new ReservationSubject();
        outputStreamCaptor = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStreamCaptor));
    }
testAttachObserver()
void ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testAttachObserver ()
Test case for attaching an observer.
Definition at line 31 of file ce204_hw4_ReservationSubjectTest.java.
                                     {
        // Arrange
        ReservationObserver observer = new User("John");
        // Act
        subject.attachObserver(observer);
        // Assert
        Assert.assertTrue(subject.getObservers().contains(observer));
    }
References ce204_hw4_library_observeMethod.ReservationSubject.attachObserver(), and ce204_hw4_library_observeMethod.ReservationSubject.getObservers().
testDetachObserver()
void ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testDetachObserver ()
Test case for detaching an observer.
Definition at line 46 of file ce204_hw4_ReservationSubjectTest.java.
                                     {
        // Arrange
        ReservationObserver observer = new User("John");
        subject.attachObserver(observer);
        // Act
        subject.detachObserver(observer);
        // Assert
        Assert.assertFalse(subject.getObservers().contains(observer));
    }
References ce204_hw4_library_observeMethod.ReservationSubject.attachObserver(), ce204_hw4_library_observeMethod.ReservationSubject.detachObserver(), and ce204_hw4_library_observeMethod.ReservationSubject.getObservers().
testNotifyObservers()
void ce204_hw4_observerMethodTest.ce204_hw4_ReservationSubjectTest.testNotifyObservers ()
Test case for notifying observers.
Definition at line 62 of file ce204_hw4_ReservationSubjectTest.java.
                                      {
        // Arrange
        ReservationObserver observer1 = new User("John");
        subject.attachObserver(observer1);
        String message = "Your reservation is confirmed.";
        // Act
        subject.notifyObservers(message);
        // Assert
        String expectedOutput = "John: Your reservation is confirmed. ";
        Assert.assertNotEquals(expectedOutput, outputStreamCaptor.toString().trim());
    }
References ce204_hw4_library_observeMethod.ReservationSubject.attachObserver(), and ce204_hw4_library_observeMethod.ReservationSubject.notifyObservers().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_observerMethodTest/ce204_hw4_ReservationSubjectTest.java