ce204_hw4_library_strategyMethod.PaymentProcessor Class Reference
Public Member Functions
void setPaymentStrategy (PaymentStrategy paymentStrategy)
void processPayment (double amount)
Detailed Description
The PaymentProcessor class is responsible for processing payments using a payment strategy.
Definition at line 6 of file PaymentProcessor.java.
Member Function Documentation
processPayment()
void ce204_hw4_library_strategyMethod.PaymentProcessor.processPayment (double amount)
Processes a payment using the specified amount.
Parameters
amount the amount to be paid
Definition at line 22 of file PaymentProcessor.java.
                                              {
        paymentStrategy.pay(amount);
    }
References ce204_hw4_library_strategyMethod.PaymentStrategy.pay().
Referenced by ce204_hw4_library_app.CarRentalApp.main(), and ce204_hw4_StrategyMethodTest.ce204_hw4_PaymentProcessorTest.testProcessPayment().
setPaymentStrategy()
void ce204_hw4_library_strategyMethod.PaymentProcessor.setPaymentStrategy (PaymentStrategy paymentStrategy)
Sets the payment strategy to be used for processing payments.
Parameters
paymentStrategy the payment strategy to be set
Definition at line 14 of file PaymentProcessor.java.
                                                                    {
        this.paymentStrategy = paymentStrategy;
    }
Referenced by ce204_hw4_library_app.CarRentalApp.main(), and ce204_hw4_StrategyMethodTest.ce204_hw4_PaymentProcessorTest.testProcessPayment().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library_strategyMethod/PaymentProcessor.java