ce204_hw4_EconomyCarTest Class Reference
Public Member Functions
void setUp ()
void testGetMileage ()
void testGetBrand ()
void testGetModel ()
void testGetYear ()
void testGetFuelType ()
void testGetGear ()
void testGetColor ()
void testGetPrice ()
void testRentCar ()
Test case for the rentCar() method.
Detailed Description
Definition at line 13 of file ce204_hw4_EconomyCarTest.java.
Member Function Documentation
setUp()
void ce204_hw4_EconomyCarTest.setUp ()
Definition at line 20 of file ce204_hw4_EconomyCarTest.java.
                        {
        carRental = new EconomyCarRental(10000, "Toyota", "Corolla", 2020, "Gasoline", "Automatic", "Red", 50);
    }
testGetBrand()
void ce204_hw4_EconomyCarTest.testGetBrand ()
< The expected brand of the car.
Definition at line 32 of file ce204_hw4_EconomyCarTest.java.
                               {
        String expectedBrand = "Toyota";
        String actualBrand = carRental.getBrand();
        Assert.assertEquals(expectedBrand, actualBrand);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getBrand().
testGetColor()
void ce204_hw4_EconomyCarTest.testGetColor ()
< The expected color of the car.
Definition at line 67 of file ce204_hw4_EconomyCarTest.java.
                               {
        String expectedColor = "Red";
        String actualColor = carRental.getColor();
        Assert.assertEquals(expectedColor, actualColor);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getColor().
testGetFuelType()
void ce204_hw4_EconomyCarTest.testGetFuelType ()
< The expected fuel type of the car.
Definition at line 53 of file ce204_hw4_EconomyCarTest.java.
                                  {
        String expectedFuelType = "Gasoline";
        String actualFuelType = carRental.getFuelType();
        Assert.assertEquals(expectedFuelType, actualFuelType);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getFuelType().
testGetGear()
void ce204_hw4_EconomyCarTest.testGetGear ()
< The expected transmission type of the car.
Definition at line 60 of file ce204_hw4_EconomyCarTest.java.
                              {
        String expectedGear = "Automatic";
        String actualGear = carRental.getGear();
        Assert.assertEquals(expectedGear, actualGear);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getGear().
testGetMileage()
void ce204_hw4_EconomyCarTest.testGetMileage ()
< The expected mileage of the car.
Definition at line 25 of file ce204_hw4_EconomyCarTest.java.
                                 {
        int expectedMileage = 10000;
        int actualMileage = carRental.getMileage();
        Assert.assertEquals(expectedMileage, actualMileage);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getMileage().
testGetModel()
void ce204_hw4_EconomyCarTest.testGetModel ()
< The expected model of the car.
Definition at line 39 of file ce204_hw4_EconomyCarTest.java.
                               {
        String expectedModel = "Corolla";
        String actualModel = carRental.getModel();
        Assert.assertEquals(expectedModel, actualModel);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getModel().
testGetPrice()
void ce204_hw4_EconomyCarTest.testGetPrice ()
< The expected price of the car rental.
Definition at line 74 of file ce204_hw4_EconomyCarTest.java.
                               {
        int expectedPrice = 50;
        int actualPrice = carRental.getPrice();
        Assert.assertEquals(expectedPrice, actualPrice);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getPrice().
testGetYear()
void ce204_hw4_EconomyCarTest.testGetYear ()
< The expected year of the car.
Definition at line 46 of file ce204_hw4_EconomyCarTest.java.
                              {
        int expectedYear = 2020;
        int actualYear = carRental.getYear();
        Assert.assertEquals(expectedYear, actualYear);
    }
References ce204_hw4_librar_factoryMethod.EconomyCarRental.getYear().
testRentCar()
void ce204_hw4_EconomyCarTest.testRentCar ()
Test case for the rentCar() method.
< Mileage of the car
< Brand of the car
< Model of the car
< Year of the car
< Fuel type of the car
< Gear type of the car
< Color of the car
< Rental price of the car
Definition at line 84 of file ce204_hw4_EconomyCarTest.java.
                              {
            
        // Test data
        int mileage = 10000;
        String brand = "Toyota";
        String model = "Corolla";
        int year = 2020;
        String fuelType = "Gasoline";
        String gear = "Automatic";
        String color = "Red";
        int price = 50;
        // Create an instance of EconomyCarRental
        EconomyCarRental carRental = new EconomyCarRental(mileage, brand, model, year, fuelType, gear, color, price);
        // Expected output
        String expectedOutput = "Brand: Toyota, Model: Corolla, Year: 2020, Fuel Type: Gasoline, Transmission: Automatic, Color: Red, Mileage: 10000, Price: 50";
        // Call rentCar() method and capture the output
        String actualOutput = captureSystemOut(carRental::rentCar);
        // Compare the expected output with the actual output
        Assert.assertEquals(expectedOutput, actualOutput);
    }
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_EconomyCarTest.java