ce204_hw4_library_observeMethod.CarReservationSystem Class Reference
Public Member Functions
void makeReservation (LocalDate startDate, int rentalDays)
void addUser (User user)
void removeUser (User user)
List< ReservationObserver > getObservers ()
Detailed Description
The CarReservationSystem class represents a car reservation system.
Definition at line 10 of file CarReservationSystem.java.
Member Function Documentation
addUser()
void ce204_hw4_library_observeMethod.CarReservationSystem.addUser (User user)
Adds a user as an observer to the reservation subject.
Parameters
user the user to be added
Definition at line 32 of file CarReservationSystem.java.
                                   {
        reservationSubject.attachObserver(user);
    }
References ce204_hw4_library_observeMethod.ReservationSubject.attachObserver().
Referenced by ce204_hw4_library_app.CarRentalApp.main(), ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.setup1(), and ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testMakeReservation().
getObservers()
List< ReservationObserver > ce204_hw4_library_observeMethod.CarReservationSystem.getObservers ()
Returns a list of observers attached to the reservation subject.
Returns
the list of observers
Definition at line 48 of file CarReservationSystem.java.
                                                    {
        return reservationSubject.getObservers();
    }
References ce204_hw4_library_observeMethod.ReservationSubject.getObservers().
Referenced by ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testRemoveUser().
makeReservation()
void ce204_hw4_library_observeMethod.CarReservationSystem.makeReservation (LocalDate startDate, int rentalDays)
Makes a car reservation with the specified start date and rental days.
Parameters
startDate the start date of the reservation
rentalDays the number of rental days
Definition at line 19 of file CarReservationSystem.java.
                                                                     {
        LocalDate endDate = startDate.plusDays(rentalDays);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        String message = "New reservation: Your rental period is from "
                + startDate.format(formatter) + " to " + endDate.format(formatter) + ".";
        reservationSubject.notifyObservers(message);
    }
References ce204_hw4_library_observeMethod.ReservationSubject.notifyObservers().
Referenced by ce204_hw4_library_app.CarRentalApp.main(), and ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testMakeReservation().
removeUser()
void ce204_hw4_library_observeMethod.CarReservationSystem.removeUser (User user)
Removes a user from the reservation subject.
Parameters
user the user to be removed
Definition at line 40 of file CarReservationSystem.java.
                                      {
        reservationSubject.detachObserver(user);
    }
References ce204_hw4_library_observeMethod.ReservationSubject.detachObserver().
Referenced by ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testRemoveUser().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library_observeMethod/CarReservationSystem.java