ce204_hw4_LuxuryCarTest Class Reference
Public Member Functions
void setUp ()
Sets up the test fixture.
void testGetMileage ()
Test case for the getMileage() method.
void testGetBrand ()
Test case for the getBrand() method.
void testGetModel ()
Test case for the getModel() method.
void testGetYear ()
Test case for the getYear() method.
void testGetFuelType ()
Test case for the getFuelType() method.
void testGetGear ()
Test case for the getGear() method.
void testGetColor ()
Test case for the getColor() method.
void testGetPrice ()
Test case for the getPrice() method.
void testRentCar ()
Test case for the rentCar() method.
Detailed Description
Definition at line 11 of file ce204_hw4_LuxuryCarTest.java.
Member Function Documentation
setUp()
void ce204_hw4_LuxuryCarTest.setUp ()
Sets up the test fixture.
Definition at line 20 of file ce204_hw4_LuxuryCarTest.java.
                        {
        carRental = new LuxuryCarRental(10000, "Toyota", "Corolla", 2020, "Gasoline", "Automatic", "Red", 50);
    }
testGetBrand()
void ce204_hw4_LuxuryCarTest.testGetBrand ()
Test case for the getBrand() method.
Definition at line 38 of file ce204_hw4_LuxuryCarTest.java.
                               {
        String expectedBrand = "Toyota";
        String actualBrand = carRental.getBrand();
        Assert.assertEquals(expectedBrand, actualBrand);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getBrand().
testGetColor()
void ce204_hw4_LuxuryCarTest.testGetColor ()
Test case for the getColor() method.
Definition at line 88 of file ce204_hw4_LuxuryCarTest.java.
                               {
        String expectedColor = "Red";
        String actualColor = carRental.getColor();
        Assert.assertEquals(expectedColor, actualColor);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getColor().
testGetFuelType()
void ce204_hw4_LuxuryCarTest.testGetFuelType ()
Test case for the getFuelType() method.
Definition at line 68 of file ce204_hw4_LuxuryCarTest.java.
                                  {
        String expectedFuelType = "Gasoline";
        String actualFuelType = carRental.getFuelType();
        Assert.assertEquals(expectedFuelType, actualFuelType);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getFuelType().
testGetGear()
void ce204_hw4_LuxuryCarTest.testGetGear ()
Test case for the getGear() method.
Definition at line 78 of file ce204_hw4_LuxuryCarTest.java.
                              {
        String expectedGear = "Automatic";
        String actualGear = carRental.getGear();
        Assert.assertEquals(expectedGear, actualGear);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getGear().
testGetMileage()
void ce204_hw4_LuxuryCarTest.testGetMileage ()
Test case for the getMileage() method.
Definition at line 28 of file ce204_hw4_LuxuryCarTest.java.
                                 {
        int expectedMileage = 10000;
        int actualMileage = carRental.getMileage();
        Assert.assertEquals(expectedMileage, actualMileage);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getMileage().
testGetModel()
void ce204_hw4_LuxuryCarTest.testGetModel ()
Test case for the getModel() method.
Definition at line 48 of file ce204_hw4_LuxuryCarTest.java.
                               {
        String expectedModel = "Corolla";
        String actualModel = carRental.getModel();
        Assert.assertEquals(expectedModel, actualModel);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getModel().
testGetPrice()
void ce204_hw4_LuxuryCarTest.testGetPrice ()
Test case for the getPrice() method.
Definition at line 98 of file ce204_hw4_LuxuryCarTest.java.
                               {
        int expectedPrice = 50;
        int actualPrice = carRental.getPrice();
        Assert.assertEquals(expectedPrice, actualPrice);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getPrice().
testGetYear()
void ce204_hw4_LuxuryCarTest.testGetYear ()
Test case for the getYear() method.
Definition at line 58 of file ce204_hw4_LuxuryCarTest.java.
                              {
        int expectedYear = 2020;
        int actualYear = carRental.getYear();
        Assert.assertEquals(expectedYear, actualYear);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.getYear().
testRentCar()
void ce204_hw4_LuxuryCarTest.testRentCar ()
Test case for the rentCar() method.
Definition at line 108 of file ce204_hw4_LuxuryCarTest.java.
                              {
        // Test data
        int mileage = 5000;
        String brand = "Mercedes";
        String model = "S-Class";
        int year = 2022;
        String fuelType = "Gasoline";
        String gear = "Automatic";
        String color = "Black";
        int price = 100;
        // Create an instance of LuxuryCarRental
        LuxuryCarRental carRental = new LuxuryCarRental(mileage, brand, model, year, fuelType, gear, color, price);
        // Expected output
        String expectedOutput = "Brand: Mercedes, Model: S-Class, Year: 2022, Fuel Type: Gasoline, Gear: Automatic, Color: Black, Mileage: 5000, Price: 100";
        // Call rentCar() method and capture the output
        String actualOutput = captureSystemOut(() -> carRental.rentCar());
        // Compare the expected output with the actual output
        Assert.assertEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_librar_factoryMethod.LuxuryCarRental.rentCar().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_LuxuryCarTest.java