ce204_hw4_librar_factoryMethod.SuvCarRental Class Reference
Public Member Functions
SuvCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
void rentCar ()
int getPrice ()
int getMileage ()
String getBrand ()
String getModel ()
int getYear ()
String getFuelType ()
String getGear ()
String getColor ()
Detailed Description
Definition at line 3 of file SuvCarRental.java.
Constructor & Destructor Documentation
SuvCarRental()
ce204_hw4_librar_factoryMethod.SuvCarRental.SuvCarRental (int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
Constructs a new SuvCarRental object with the specified details.
Parameters
mileage the mileage of the car
brand the brand of the car
model the model of the car
year the year of the car
fuelType the fuel type of the car
gear the transmission type of the car
color the color of the car
price the price of the car rental
Definition at line 25 of file SuvCarRental.java.
                                                                                                                                  {
        this.mileage = mileage;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.fuelType = fuelType;
        this.gear = gear;
        this.color = color;
        this.price = price;
    }
Member Function Documentation
getBrand()
String ce204_hw4_librar_factoryMethod.SuvCarRental.getBrand ()
Returns the brand of the SUV car.
Returns
the brand of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 72 of file SuvCarRental.java.
                             {
        // TODO Auto-generated method stub
        return brand;
    }
Referenced by ce204_hw4_SUVCarTest.testGetBrand().
getColor()
String ce204_hw4_librar_factoryMethod.SuvCarRental.getColor ()
Returns the color of the SUV car.
Returns
the color of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 122 of file SuvCarRental.java.
                             {
        // TODO Auto-generated method stub
        return color;
    }
Referenced by ce204_hw4_SUVCarTest.testGetColor().
getFuelType()
String ce204_hw4_librar_factoryMethod.SuvCarRental.getFuelType ()
Returns the fuel type of the SUV car.
Returns
the fuel type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 102 of file SuvCarRental.java.
                                {
        // TODO Auto-generated method stub
        return fuelType;
    }
Referenced by ce204_hw4_SUVCarTest.testGetFuelType().
getGear()
String ce204_hw4_librar_factoryMethod.SuvCarRental.getGear ()
Returns the transmission type of the SUV car.
Returns
the transmission type of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 112 of file SuvCarRental.java.
                            {
        // TODO Auto-generated method stub
        return gear;
    }
Referenced by ce204_hw4_SUVCarTest.testGetGear().
getMileage()
int ce204_hw4_librar_factoryMethod.SuvCarRental.getMileage ()
Returns the mileage of the SUV car.
Returns
the mileage of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 62 of file SuvCarRental.java.
                            {
        // TODO Auto-generated method stub
        return mileage;
    }
Referenced by ce204_hw4_SUVCarTest.testGetMileage().
getModel()
String ce204_hw4_librar_factoryMethod.SuvCarRental.getModel ()
Returns the model of the SUV car.
Returns
the model of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 82 of file SuvCarRental.java.
                             {
        // TODO Auto-generated method stub
        return model;
    }
Referenced by ce204_hw4_SUVCarTest.testGetModel().
getPrice()
int ce204_hw4_librar_factoryMethod.SuvCarRental.getPrice ()
Returns the price of the SUV car rental.
Returns
the price of the car rental
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 52 of file SuvCarRental.java.
                          {
        // TODO Auto-generated method stub
        return price;
    }
Referenced by ce204_hw4_SUVCarTest.testGetPrice().
getYear()
int ce204_hw4_librar_factoryMethod.SuvCarRental.getYear ()
Returns the year of the SUV car.
Returns
the year of the car
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 92 of file SuvCarRental.java.
                         {
        // TODO Auto-generated method stub
        return year;
    }
Referenced by ce204_hw4_SUVCarTest.testGetYear().
rentCar()
void ce204_hw4_librar_factoryMethod.SuvCarRental.rentCar ()
Rents the SUV car and prints its details.
Implements ce204_hw4_librar_factoryMethod.ICarRental.
Definition at line 40 of file SuvCarRental.java.
                          {
        // TODO Auto-generated method stub
        System.out.println("Brand: " + brand + ", Model: " + model + ", Year: " + year +
                ", Fuel Type: " + fuelType + ", Transmission: " + gear + ", Color: " + color +
                ", Mileage: " + mileage + ", Price: " + price);
    }
Referenced by ce204_hw4_SUVCarTest.testRentCar().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_librar_factoryMethod/SuvCarRental.java