ce204_hw4_librar_factoryMethod.RentalFactory Class Reference
Public Member Functions
ICarRental createRental (String type, int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
Detailed Description
Definition at line 3 of file RentalFactory.java.
Member Function Documentation
createRental()
ICarRental ce204_hw4_librar_factoryMethod.RentalFactory.createRental (String type, int mileage, String brand, String model, int year, String fuelType, String gear, String color, int price)
Creates a car rental based on the specified type and details.
Parameters
type the type of the car rental
mileage the mileage of the car
brand the brand of the car
model the model of the car
year the year of the car
fuelType the fuel type of the car
gear the transmission type of the car
color the color of the car
price the price of the car rental
Returns
an instance of the specified car rental type
Definition at line 18 of file RentalFactory.java.
                                                                                                                                                          {
        ICarRental carRental = null;
        switch (type) {
            case "economy":
                 // Creates an instance of EconomyCarRental
                carRental = new EconomyCarRental(mileage, brand, model, year, fuelType, gear, color, price);
                break;
            case "luxury":
                 // Creates an instance of LuxuryCarRental
                carRental = new LuxuryCarRental(mileage, brand, model, year, fuelType, gear, color, price);
                break;
            case "suv":
                // Creates an instance of SuvCarRental
                carRental = new SuvCarRental(mileage, brand, model, year, fuelType, gear, color, price);
                break;
        }
        return carRental;
    }
Referenced by ce204_hw4_library_app.CarRentalApp.main(), ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_librar_factoryMethod/RentalFactory.java