ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest Class Reference
Public Member Functions
void setup ()
Set up the test environment.
void testMakeReservation ()
Test case for making a reservation.
void setup1 ()
Set up the test environment.
void testRemoveUser ()
Test case for removing a user.
Detailed Description
Definition at line 17 of file ce204_hw4_CarReservationSystemTest.java.
Member Function Documentation
setup()
void ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.setup ()
Set up the test environment.
Definition at line 26 of file ce204_hw4_CarReservationSystemTest.java.
                            {
            carReservationSystem = new CarReservationSystem();
            outputStreamCaptor = new ByteArrayOutputStream();
            System.setOut(new PrintStream(outputStreamCaptor));
        }
setup1()
void ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.setup1 ()
Set up the test environment.
Definition at line 63 of file ce204_hw4_CarReservationSystemTest.java.
                             {
            reservationSystem = new CarReservationSystem();
            user1 = new User("John");
            user2 = new User("Jane");
            reservationSystem.addUser(user1);
            reservationSystem.addUser(user2);
        }
References ce204_hw4_library_observeMethod.CarReservationSystem.addUser().
testMakeReservation()
void ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testMakeReservation ()
Test case for making a reservation.
Definition at line 36 of file ce204_hw4_CarReservationSystemTest.java.
                                          {
            // Arrange
            LocalDate startDate = LocalDate.now();
            int rentalDays = 5;
            LocalDate endDate = startDate.plusDays(rentalDays);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            String expectedMessage = "New reservation: Your rental period is from "
                    + startDate.format(formatter) + " to " + endDate.format(formatter) + ".";
            User user1 = new User("John");
            carReservationSystem.addUser(user1);
            // Act
            carReservationSystem.makeReservation(startDate, rentalDays);
            // Assert
            String expectedOutput = "John: " + expectedMessage;
            Assert.assertEquals(expectedOutput, outputStreamCaptor.toString().trim());
        }
References ce204_hw4_library_observeMethod.CarReservationSystem.addUser(), and ce204_hw4_library_observeMethod.CarReservationSystem.makeReservation().
testRemoveUser()
void ce204_hw4_observerMethodTest.ce204_hw4_CarReservationSystemTest.testRemoveUser ()
Test case for removing a user.
Definition at line 75 of file ce204_hw4_CarReservationSystemTest.java.
                                     {
            // Arrange
            // Act
            reservationSystem.removeUser(user1);
            // Assert
            Assert.assertFalse(reservationSystem.getObservers().contains(user1));
            Assert.assertTrue(reservationSystem.getObservers().contains(user2));
        }
References ce204_hw4_library_observeMethod.CarReservationSystem.getObservers(), and ce204_hw4_library_observeMethod.CarReservationSystem.removeUser().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_observerMethodTest/ce204_hw4_CarReservationSystemTest.java