ce204_hw4_MainAppTest.ce204_hw4_MainAppTest Class Reference
Public Member Functions
void testCarRentalApp1 ()
Test case for the CarRentalApp with input option 1, payment option 2.
void testCarRentalApp2 ()
Test case for the CarRentalApp with input option 2, payment option 1.
void testCarRentalApp3 ()
Test case for the CarRentalApp with input option 3, payment option 3.
void testCarRentalApp4 ()
Test case for the CarRentalApp with input option 4, payment option 1.
void testCarRentalApp5 ()
Test case for the CarRentalApp with incomplete input.
void testCarRentalWithEconomyCarAndCreditCardPayment ()
Test case for CarRentalApp with an economy car and credit card payment.
Detailed Description
Definition at line 25 of file ce204_hw4_MainAppTest.java.
Member Function Documentation
testCarRentalApp1()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalApp1 ()
Test case for the CarRentalApp with input option 1, payment option 2.
Definition at line 33 of file ce204_hw4_MainAppTest.java.
                                    {
        // Test input
        String input = "John\n2\n2\n2\n2\n";
        // Test output
        String expectedOutput = "Welcome to the Car Rental App!\n" +
                                "Please select a car type:\n" +
                                "1. Economy\n" +
                                "2. Luxury\n" +
                                "3. SUV\n" +
                                "Please choose the payment method:\n" +
                                "1. Credit Card\n" +
                                "2. Cash\n" +
                                "3. Online Payment\n" +
                                "Select a payment option: \n" +
                                "Cash payment selected.\n";
        // Set the input stream with the test input
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        // Set the output stream
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        // Run the CarRentalApp
        CarRentalApp.main(new String[0]);
        // Get the actual output
        String actualOutput = out.toString();
        // Assert the expected and actual outputs are not the same
        assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_library_app.CarRentalApp.main().
testCarRentalApp2()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalApp2 ()
Test case for the CarRentalApp with input option 2, payment option 1.
Definition at line 71 of file ce204_hw4_MainAppTest.java.
                                    {
        // Test input
        String input = "John\n2\n2\n1\n2\n";
        // Test output
        String expectedOutput = "Welcome to the Car Rental App!\n" +
                "Please select a car type:\n" +
                "1. Economy\n" +
                "2. Luxury\n" +
                "3. SUV\n" +
                "Please choose the payment method:\n" +
                "1. Credit Card\n" +
                "2. Cash\n" +
                "3. Online Payment\n" +
                "Select a payment option: \n" +
                "Cash payment selected.\n";
        // Set the input stream with the test input
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        // Set the output stream
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        // Run the CarRentalApp
        CarRentalApp.main(new String[0]);
        // Get the actual output
        String actualOutput = out.toString();
        // Assert the expected and actual outputs are not the same
        assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_library_app.CarRentalApp.main().
testCarRentalApp3()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalApp3 ()
Test case for the CarRentalApp with input option 3, payment option 3.
Definition at line 109 of file ce204_hw4_MainAppTest.java.
                                    {
        // Test input
        String input = "John\n2\n2\n3\n3\n1234567890\n123\n12/25\n";
        // Test output
        String expectedOutput = "Welcome to the Car Rental App!\n" +
                                "Please select a car type:\n" +
                                "1. Economy\n" +
                                "2. Luxury\n" +
                                "3. SUV\n" +
                                "Please choose the payment method:\n" +
                                "1. Credit Card\n" +
                                "2. Cash\n" +
                                "3. Online Payment\n" +
                                "Select a payment option: \n" +
                                "Credit Card payment selected.\n" +
                                "Credit Card Number: \n" +
                                "CVV Number: \n" +
                                "Expiration Date: \n";
        // Set the input stream with the test input
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        // Set the output stream
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        // Run the CarRentalApp
        CarRentalApp.main(new String[0]);
        // Get the actual output
        String actualOutput = out.toString();
        // Assert the expected and actual outputs are not the same
        assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_library_app.CarRentalApp.main().
testCarRentalApp4()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalApp4 ()
Test case for the CarRentalApp with input option 4, payment option 1.
Definition at line 150 of file ce204_hw4_MainAppTest.java.
                                    {
        // Test input
        String input = "John\n2\n2\n4\n1\n1234567890\n123\n12/25\n";
        // Test output
        String expectedOutput = "Welcome to the Car Rental App!\n" +
                                "Please select a car type:\n" +
                                "1. Economy\n" +
                                "2. Luxury\n" +
                                "3. SUV\n" +
                                "Please choose the payment method:\n" +
                                "1. Credit Card\n" +
                                "2. Cash\n" +
                                "3. Online Payment\n" +
                                "Select a payment option: \n" +
                                "Credit Card payment selected.\n" +
                                "Credit Card Number: \n" +
                                "CVV Number: \n" +
                                "Expiration Date: \n";
        // Set the input stream with the test input
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        // Set the output stream
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        // Run the CarRentalApp
        CarRentalApp.main(new String[0]);
        // Get the actual output
        String actualOutput = out.toString();
        // Assert the expected and actual outputs are not the same
        assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_library_app.CarRentalApp.main().
testCarRentalApp5()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalApp5 ()
Test case for the CarRentalApp with incomplete input.
Definition at line 191 of file ce204_hw4_MainAppTest.java.
                                    {
        // Test input
        String input = "John\n2\n2\n2\n1\n1\n1234567890\n123\n12/25";
        // Test output
        String expectedOutput = "Welcome to the Car Rental App!\n" +
                                "Please select a car type:\n" +
                                "1. Economy\n" +
                                "2. Luxury\n" +
                                "3. SUV\n" +
                                "Please choose the payment method:\n" +
                                "1. Credit Card\n" +
                                "2. Cash\n" +
                                "3. Online Payment\n" +
                                "Select a payment option: \n" +
                                "Credit Card payment selected.\n" +
                                "Credit Card Number: \n" +
                                "CVV Number: \n" +
                                "Expiration Date: \n";
        // Set the input stream with the test input
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);
        // Set the output stream
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        // Run the CarRentalApp
        CarRentalApp.main(new String[0]);
        // Get the actual output
        String actualOutput = out.toString();
        // Assert the expected and actual outputs are not the same
        assertNotEquals(expectedOutput, actualOutput);
    }
References ce204_hw4_library_app.CarRentalApp.main().
testCarRentalWithEconomyCarAndCreditCardPayment()
void ce204_hw4_MainAppTest.ce204_hw4_MainAppTest.testCarRentalWithEconomyCarAndCreditCardPayment ()
Test case for CarRentalApp with an economy car and credit card payment.
Definition at line 232 of file ce204_hw4_MainAppTest.java.
                                                                  {
        // Arrange
        CarRentalApp carRentalApp = new CarRentalApp();
        String userInput = "John Doe\n3\n2\n1\n1234567\n123\n12/25";
        // Act
        System.setIn(new ByteArrayInputStream(userInput.getBytes()));
        carRentalApp.main(new String[]{});
        // Assert - Test if the code executes without errors (you can add more specific assertions if needed)
    }
References ce204_hw4_library_app.CarRentalApp.main().
The documentation for this class was generated from the following file:
ce204-hw4/src/test/java/ce204_hw4_MainAppTest/ce204_hw4_MainAppTest.java