ce204_hw4_library_strategyMethod.PaymentStrategy Interface Reference
Public Member Functions
void pay (double amount)
Detailed Description
The PaymentStrategy interface represents a payment strategy.
Definition at line 6 of file PaymentStrategy.java.
Member Function Documentation
pay()
void ce204_hw4_library_strategyMethod.PaymentStrategy.pay (double amount)
Performs a payment transaction.
Parameters
amount the amount to be paid
Implemented in ce204_hw4_library_strategyMethod.CashPayment, ce204_hw4_library_strategyMethod.CreditCardPayment, and ce204_hw4_library_strategyMethod.OnlinePayment.
Referenced by ce204_hw4_library_strategyMethod.PaymentProcessor.processPayment(), ce204_hw4_StrategyMethodTest.ce204_hw4_CashPaymentTest.testPay(), ce204_hw4_StrategyMethodTest.ce204_hw4_CreditCardMethodTest.testPay(), and ce204_hw4_StrategyMethodTest.ce204_hw4_OnlinePaymentTest.testPay().
The documentation for this interface was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library_strategyMethod/PaymentStrategy.java