ce204_hw4_librar_factoryMethod.ICarRental Interface Reference
Public Member Functions
void rentCar ()
int getMileage ()
String getBrand ()
String getModel ()
int getYear ()
String getFuelType ()
String getGear ()
String getColor ()
int getPrice ()
Detailed Description
Author
opola
Definition at line 8 of file ICarRental.java.
Member Function Documentation
getBrand()
String ce204_hw4_librar_factoryMethod.ICarRental.getBrand ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getColor()
String ce204_hw4_librar_factoryMethod.ICarRental.getColor ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getFuelType()
String ce204_hw4_librar_factoryMethod.ICarRental.getFuelType ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getGear()
String ce204_hw4_librar_factoryMethod.ICarRental.getGear ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getMileage()
int ce204_hw4_librar_factoryMethod.ICarRental.getMileage ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getModel()
String ce204_hw4_librar_factoryMethod.ICarRental.getModel ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getPrice()
int ce204_hw4_librar_factoryMethod.ICarRental.getPrice ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_library_app.CarRentalApp.main(), ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
getYear()
int ce204_hw4_librar_factoryMethod.ICarRental.getYear ()
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_RentalFactoryTest.testCreateRental_EconomyCar(), ce204_hw4_RentalFactoryTest.testCreateRental_LuxuryCar(), and ce204_hw4_RentalFactoryTest.testCreateRental_SuvCar().
rentCar()
void ce204_hw4_librar_factoryMethod.ICarRental.rentCar ()
   //The code defines an interface named ICarRental. An interface is a contract that defines a set of methods that a class implementing the interface must provide.
 The interface declares several method signatures: rentCar() is a method without a return type (void). It represents the action of renting a car. getMileage() is a method that returns an integer. It represents getting the mileage of the car. getBrand() is a method that returns a string. It represents getting the brand of the car. getModel() is a method that returns a string. It represents getting the model of the car. getYear() is a method that returns an integer. It represents getting the year of the car. getFuelType() is a method that returns a string. It represents getting the fuel type of the car. getGear() is a method that returns a string. It represents getting the gear type of the car. getColor() is a method that returns a string. It represents getting the color of the car. getPrice() is a method that returns an integer. It represents getting the price of the car rental. The purpose of this interface is to provide a contract or blueprint for classes that represent different types of car rentals. By implementing this interface, a class must provide implementations for all the methods declared in the interface. In other words, any class that wants to be considered a car rental must implement these methods to define how renting a car works and how to retrieve specific details of the car.
Implemented in ce204_hw4_librar_factoryMethod.EconomyCarRental, ce204_hw4_librar_factoryMethod.LuxuryCarRental, and ce204_hw4_librar_factoryMethod.SuvCarRental.
Referenced by ce204_hw4_library_app.CarRentalApp.main().
The documentation for this interface was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_librar_factoryMethod/ICarRental.java